apiVersion: v1
kind: Service
metadata:
  name: learner-service-loadbalancer
spec:
  selector:
    app: learner-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8003
  type: LoadBalancer
